name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      env:
        CI: true
      run: |
        npm install
        npm run build --if-present
    - name: deploy
      run: |
        git clone git@github.com:bloriot97/bloriot97.github.io.git
        rm -rf ./bloriot97.github.io/*
        cp -r ./dist/ ./bloriot97.github.io
        cd ./bloriot97.github.io
        git config --global user.email "bloriot97@gmail.com"
        git config --global user.name "GH CI Benjamin Loriot"
        git add .
        git commit -m 'Deploy '$GITHUB_SHA
        git push
