name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      env:
        CI: true
      run: |
        npm install
        npm run build --if-present
        pwd 
        mkdir /home/runner/.ssh
        echo '${{ secrets.ssh_key }}' > /home/runner/.ssh/id_rsa
        head /home/runner/.ssh/id_rsa
        chmod 400 /home/runner/.ssh/id_rsa
        eval `ssh-agent -s`
        ssh-add /home/runner/.ssh/id_rsa
        git clone git@github.com:bloriot97/bloriot97.github.io.git
        ls -al
        ls -al ./bloriot97.github.io.git
